---
- name: Installing andrewrothstein.unarchiedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.gcc_toolbox
  ansible.builtin.include_role:
    name: andrewrothstein.gcc_toolbox
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading src...
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ libyajl_tgz_url }}'
    dest: '{{ libyajl_tmp_tgz }}'
    mode: '644'
- name: Unarchive...
  become: true
  become_user: root
  ansible.builtin.unarchive:
    remote_src: true
    src: '{{ libyajl_tmp_tgz }}'
    dest: '{{ libyajl_parent_src_dir }}'
    creates: '{{ libyajl_src_dir }}'
- name: Configure...
  become: true
  become_user: root
  ansible.builtin.command: '{{ libyafl_src_dir }}/configure'
  args:
    chdir: '{{ libyajl_src_dir }}'
    creates: '{{ libyafl_src_dir }}/Makefile'
- name: Make Install...
  become: true
  become_user: root
  ansible.builtin.command: make install
  changed_when: false
  args:
    chdir: '{{ libyajl_src_dir }}'
- name: Cleanup...
  become: true
  become_user: root
  ansible.builtin.file:
    path:
      - '{{ libyajl_src_dir }}'
      - '{{ libyafl_tmp_tgz }}'
    state: absent
